### ISSUE TITLE
Not available on the marketplace

### ISSUE THREAD

**Issue by petervdbroek-retail** [RubinCarter/gitflow4idea-fix#2]
* **I'm submitting a ...**
  - [ x ] bug report

* **What is the current behavior?**
Not showing up on marketplace of IntelliJ, neither on the website nor in the application

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. Open plugins
3. Search for Git Flow

* **What is the expected behavior?**
Show gitflow plugin able to install

* **What is the motivation / use case for changing the behavior?**
People are able to install the plugin

* **Please tell me about your environment:**
  ~~~~
  Gitflow version: 1.11.0 (AVH Edition)
  PhpStorm 2021.3.1
  Build #PS-213.6461.83, built on December 29, 2021
  Runtime version: 11.0.13+7-b1751.21 amd64
  VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  Linux 4.15.0-163-generic
  Current Desktop: KDE
  ~~~~

And kudos for picking up the gauntlet! Using this plugin a lot but it has been out of sync with idea version a lot too.

**Comment by RubinCarter** [comment]
@petervdbroek-retail Hello, I have pushed to the market and is under review. has been placed on the website, you can download and install it manually

**Comment by RubinCarter** [comment]
see https://www.jetbrains.com/help/idea/managing-plugins.html?keymap=primary_windows#install_plugin_from_disk

**Comment by RubinCarter** [comment]
see https://www.jetbrains.com/help/phpstorm/managing-plugins.html?keymap=primary_windows#install_plugin_from_disk

**Comment by saschaglo** [comment]
Hey @RubinCarter , what do you mean with "has been placed on website", which website? Want to use it ASAP, have seen your change and I am not familiar with JAVA, therefore can't build it by myself but as mentioned, want to use it ASAP. Please give me a hint on what you mean with "has been placed on website" so I can download & use it prior to the finished review... Thanks in advance :)

**Comment by RubinCarter** [comment]
@saschaglo hi,You can check that the release of this project already contains the installation files
![image](https://user-images.githubusercontent.com/13096279/148727375-e3f734e8-32b7-469c-a692-11c807e9ebc2.png)

**Comment by RubinCarter** [comment]
@saschaglo download URL https://github.com/RubinCarter/gitflow4idea-fix/releases/download/0.7.8/gitflow4idea-fix-0.7.8.zip

**Comment by saschaglo** [comment]
Perfect. Thanks!

**Comment by RubinCarter** [comment]
The plugin is available via the IntelliJ plugin manager. Just search for "Git Flow Integration Fix" to get the latest version!
